name: code coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        command: dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage  --no-build --verbosity normal 
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: ${{ github.ref == 'refs/heads/main' }}
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
