name: code coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Coverage xml file
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: ${{ github.ref == 'refs/heads/main' }}
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
