name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
       pull-requests: write

    env:
      COVERAGE_PASS_THRESHOLD: ${{ secrets.COVERAGE_PASS_THRESHOLD || '80' }}
      COVERAGE_HEALTHY_THRESHOLD: ${{ secrets.COVERAGE_HEALTHY_THRESHOLD || '90' }}
        
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage  --no-build --verbosity normal

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: ${{ github.ref == 'refs/heads/main' }} 
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '${{ env.COVERAGE_PASS_THRESHOLD }} ${{ env.COVERAGE_HEALTHY_THRESHOLD }}'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY